# Generated by Django 5.2.4 on 2025-07-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
