# Generated by Django 5.2.4 on 2025-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_author_alter_article_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
